config/routes.rb
Rails.application.routes.draw do

  root to: 'public#index'

  get 'show/:permalink', to: 'public#show', as: 'public_show'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

end

app/models/section.rb
class Section < ApplicationRecord

  acts_as_list scope: :page

  belongs_to :page
  has_many :section_edits
  has_many :admin_users, through: :section_edits

  scope :visible, lambda { where(visible: true) }
  scope :invisible, lambda { where(visible: false) }
  scope :sorted, lambda { order('position ASC') }
  scope :newest_first, lambda { order('created_at DESC') }

  CONTENT_TYPES = %w[text HTML].freeze

  validates :name, presence: true,
                   length: { maximum: 255 }
  validates_inclusion_of :content_type, in: CONTENT_TYPES,
                                        message: "must be one of: #{CONTENT_TYPES.join(', ')}"
  validates_presence_of :content

  validate :image_size_validation

  mount_uploader :image, ImageUploader
  mount_uploader :audio, AudioUploader
  mount_uploader :video, VideoUploader

  private

  def image_size_validation
    errors[:image] << 'should be less than 500KB' if image.size > 0.5.megabytes
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_page
  before_action :set_section_count, only: %i[new create edit update]

  def index
    @sections = @page.sections.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new(page_id: @page.id)
  end

  def create
    @section = Section.new(section_params)
    @section.page = @page
    if @section.save
      # If save succeeds, redirect to the index action
      notice_str = 'Section created successfully.'
      redirect_to sections_path(page_id: @page.id), notice: notice_str
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    # Find a new object using form parameters
    @section = Section.find(params[:id])
    # update the object
    if @section.update_attributes(section_params)
      notice_str = 'Section updated successfully.'
      redirect_to sections_path(page_id: @page.id), notice: notice_str
    else
      # If save fails, redisplay the form so user can fix problems
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = 'Section destroyed successfully.'
    redirect_to(sections_path(page_id: @page.id))
  end

  private

  def section_params
    params.require(:section).permit(:name, :position, :visible, :content_type, :content, :image, :audio, :video)
  end

  def find_page
    @page = Page.find(params[:page_id])
  end

  def set_section_count
    @section_count = @page.sections.count
    @section_count += 1 if params[:action] == 'new' || params[:action] == 'create'
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_area(:name, :size => '40x10') %>
</div>
<div class="field">
  <%= f.label :position %><br>
  <%= f.select(:position, 1..@section_count) %>
</div>
<div class="field">
  <%= f.label :visible %><br>
  <%= f.check_box(:visible) %>
</div>
<div class="field">
  <%= f.label :content_type %><br>
  <%= f.radio_button(:content_type, 'text') %> Text
  <%= f.radio_button(:content_type, 'HTML') %> HTML
</div>
<div class="field">
  <%= f.label :content %><br>
  <%= f.text_area(:content, :size => '40x10') %>
</div>
<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
  <% if f.object.image? %>
    <%= image_tag f.object.image.thumb.url %>
    <%= f.label :remove_image %>
    <%= f.check_box :remove_image %>
  <% end %>
</div>
<div class="field">
  <%= f.label :audio %><br>
  <%= f.file_field :audio %>
  <% if f.object.audio? %>
    <%= f.label :remove_audio %>
    <%= f.check_box :remove_audio %>
  <% end %>
</div>
<div class="field">
  <%= f.label :video %><br>
  <%= f.file_field :video %>
  <% if f.object.video? %>
    <%= f.label :remove_video %>
    <%= f.check_box :remove_video %>
  <% end %>
</div>

app/views/sections/delete.html.erb
<% @page_title = "Delete Section" %>

<%= link_to("<< Back to List", sections_path(page_id: @page.id), class: 'back-link') %>

<div class="sections delete">
    <h2>Delete Section</h2>

    <%= form_for(@section, url: section_path(@section, page_id: @page.id), method: 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this section?</p>

      <p class="reference-name"><%= f.object.name %></p>

      <div class="form-buttons">
        <%= f.submit("Delete Section") %>
      </div>

   <% end %>
</div>

app/views/sections/edit.html.erb
<% @page_title = "Edit Section" %>

<%= link_to("<< Back to List", sections_path(:page_id => @page.id), :class => 'back-link') %>

<div class="sections edit">
    <h2>Update Section</h2>

    <%= form_for(@section, :url => section_path(@section, :page_id => @page.id)) do |f| %>

      <%= render(:partial => 'form', :locals => {:f => f, :section => @section}) %>

      <div class="form-buttons">
        <%= f.submit("Update Section") %>
      </div>

    <% end %>
</div>

app/views/sections/index.html.erb
<% @page_title = "All Sections" %>

<%= link_to("<< Back to Pages", pages_path(subject_id: @page.subject_id), class: 'back-link') %>

<div class="section index">
  <h2>Sections</h2>

  <%= image_tag('plus_sign.png', size: '11x11', alt: '+') %>
  <%= link_to("Add New Section", new_section_path(page_id: @page.id), class: 'action new') %>

  <table class="listing" summary="Section list">
    <tr class="header">
      <th>#</th>
      <th>Page ID</th>
      <th>Section</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
        <td><%= section.position %></td>
        <td><%= section.page_id %></td>
        <td><%= section.name %></td>
        <td class="center"><%= status_tag(section.visible) %></td>
        <td class="actions">
          <%= link_to("Show", section_path(section, page_id: @page.id), class: 'action show') %>
          <%= link_to("Edit", edit_section_path(section, page_id: @page.id), class: 'action edit') %>
          <%= link_to("Delete", delete_section_path(section, page_id: @page.id), class: 'action delete') %>
        </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<% @page_title = "New Section" %>

<%= link_to("<< Back to List", sections_path(page_id: @page.id), class: 'back-link') %>

<div class="sections new">
    <h2>Create Section</h2>

    <%= form_for(@section, url: sections_path(page_id: @page.id)) do |f| %>

      <%= render(partial: 'form', locals: {f: f, section: @section}) %>

      <div class="form-buttons">
        <%= f.submit('Create Section') %>
      </div>

    <% end %>
</div>

app/views/sections/show.html.erb
<% @page_title = "Show Section" %>

<%= link_to("<< Back to List", sections_path(page_id: @page.id), class: 'back-link') %>

<div class="sections show">
  <h2>Show Section</h2>

  <table summary="Section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Page ID</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Image:</th>
      <td><%= image_tag @section.image_url(:thumb) if @section.image?  %></td>
    </tr>
    <tr>
      <th>Audio:</th>
      <td><%= audio_tag(@section.audio_url, autoplay: false, controls: true) if @section.audio? %></td>
    </tr>
    <tr>
      <th>Video:</th>
      <td><%= video_tag(@section.video_url, autoplay: false, controls: true) if @section.video? %></td>
    </tr>    
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>